version: '2'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  website:
    image: image_to_image_search:version3
    volumes:
      - ~/.keras:/root/.keras
    ports:
      - "7001:5000"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    working_dir: /image_search
    command: python3 server.py
